Models/Pager.cs
namespace CrudApplication1.Models
{
    public class Pager
    {
        public string searchString { get; set; }
        public string sortBy { get; set; } = string.Empty;
        public string sortDirection { get; set; } = string.Empty;
        
        public string Controller { get; set; }
        public string Action { get; set; }


        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }
        public Pager()
        {

        }
        //        public Pager(int totalItems, int page, int pageSize)
        public Pager(int totalItems, int page, int pageSize, string sortBy = "" , string sortDirection = "")
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if(startPage <=0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }
            if(endPage > totalPages)
            {
                endPage = totalPages;
                if(endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }
            TotalItems = totalItems;         
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;

            this.sortBy = sortBy;
            this.sortDirection = sortDirection;

        }
    }

    
}

Models/Sorting.cs
namespace CrudApplication1.Models
{
    public class Sorting
    {
        public string SortByName { get; set; }
        public string SortByCity { get; set; }
        public string SortByState { get; set; }
        public string SortBySalary { get; set; }
    }

}

Controllers/EmpDataController.cs
using CrudApplication.Data;
using CrudApplication1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CrudApplication1.Controllers
{
    public class EmpDataController : Controller
    {
        private ApplicationContext context;

        public EmpDataController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            
            return View();
        }
        public IActionResult Detail(string searchString = "", string searchBy = "") 
        {
                IQueryable<Employee> employees = context.Employees;
                switch (searchBy)
                {
                    case "id":
                    if (decimal.TryParse(searchString, out decimal empId))
                    {
                        employees = employees.Where(p => p.Id == empId);
                    }
                        break;
                    case "name":
                        employees = employees.Where(p => p.Name.Contains(searchString));
                        break;
                    case "city":
                        employees = employees.Where(p => p.City.Contains(searchString));
                        break;
                    case "state":
                        employees = employees.Where(p => p.State.Contains(searchString));
                        break;
                    case "salary":
                        if (decimal.TryParse(searchString, out decimal minSalary))
                        {
                            employees = employees.Where(p => p.Salary >= minSalary);
                        }
                        break;
                    default:
                     employees = employees.Where(p => p.Name.Contains(searchString));
                    break;
                }
               return View(employees.ToList());
         }
        public IActionResult Back()
        {
            return RedirectToAction("Index");
        }

    }
    
}

Controllers/EmployeeController.cs
using CrudApplication.Data;
using CrudApplication1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace CrudApplication1.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationContext context;
        public EmployeeController(ApplicationContext context)
        {
            this.context = context;
        }
        public IActionResult Index(string sortDirection = "", string sortBy = "", int pg = 1)
        {
            IQueryable<Employee> employees = context.Employees;

            switch (sortBy)
            {
                case "Id":
                    employees = (sortDirection == "asc") ? employees.OrderBy(p => p.Id) : employees.OrderByDescending(p => p.Id);
                    break;

                case "Name":
                    employees = (sortDirection == "asc") ? employees.OrderBy(p => p.Name) : employees.OrderByDescending(p => p.Name);
                    break;

                case "City":
                    employees = (sortDirection == "asc") ? employees.OrderBy(p => p.City) : employees.OrderByDescending(p => p.City);
                    break;

                case "State":
                    employees = (sortDirection == "asc") ? employees.OrderBy(p => p.State) : employees.OrderByDescending(p => p.State);
                    break;
                
                case "Salary":
                    employees = (sortDirection == "asc") ? employees.OrderBy(p => p.Salary) : employees.OrderByDescending(p => p.Salary);
                    break;

                default:
                    employees = employees.OrderBy(p => p.Id);
                    break;
            }

            const int pageSize = 10;

            if (pg < 1)
            {
                pg = 1;
            }

            int resCount = employees.Count();

            var pager = new Pager(resCount, pg, pageSize, sortBy, sortDirection);

            int recSkip = (pg - 1) * pageSize;

            var data = employees.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee model)
        {
            if (ModelState.IsValid)
            {
                var emp = new Employee()
                {
                   Name=model.Name,
                   City=model.City,
                   State=model.State,
                   Salary=model.Salary
                };
                context.Employees.Add(emp);
                context.SaveChanges();
                TempData["error"] = "Record Saved Successfully";
                return RedirectToAction("Index");
            }
           else
           {
                TempData["error"] = "Empty field cant submit";
                return View(model);

           }
        }
        //[HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var emp = context.Employees.SingleOrDefault(e => e.Id == id);
            context.Employees.Remove(emp);
            context.SaveChanges();
            TempData["error"] = "Record Deleted Successfully";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var emp = context.Employees.SingleOrDefault(e => e.Id == id);
            var result = new Employee()
            {
                Name = emp.Name,
                City = emp.City,
                State = emp.State,
                Salary = emp.Salary
            };
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(Employee model)
        {
            var emp = new Employee()
            {
                Id=model.Id,
                Name = model.Name,
                City = model.City,
                State = model.State,
                Salary = model.Salary
            };
            context.Employees.Update(emp);
            context.SaveChanges();
            TempData["error"] = "Record Updated Successfully";
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Data</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmpData" asp-action="Index">EmpData</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CrudApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Pager.cshtml
@model CrudApplication1.Models.Pager
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">

    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {

                <li class="page-item">

                    <a class="page-link" asp-controller="Employee" asp-action="Index" asp-route-sortBy="@(Model.sortBy)" asp-route-sortDirection="@(Model.sortDirection)" asp-route-pg="1">

                        First

                    </a>

                </li>

                <li class="page-item">

                    <a class="page-link" asp-controller="Employee" asp-action="Index" asp-route-sortBy="@(Model.sortBy)" asp-route-sortDirection="@(Model.sortDirection)" asp-route-pg="@(Model.CurrentPage - 1)">

                        Previous

                    </a>

                </li>

            }

            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {

                <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">

                    <a class="page-link" asp-controller="Employee" asp-action="Index" asp-route-sortBy="@(Model.sortBy)" asp-route-sortDirection="@(Model.sortDirection)" asp-route-pg="@pge">

                        @pge

                    </a>

                </li>

            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">

                    <a class="page-link" asp-controller="Employee" asp-action="Index" asp-route-sortBy="@(Model.sortBy)" asp-route-sortDirection="@(Model.sortDirection)" asp-route-pg="@(Model.CurrentPage + 1)">

                        Next

                    </a>

                </li>

                <li class="page-item">

                    <a class="page-link" asp-controller="Employee" asp-action="Index" asp-route-sortBy="@(Model.sortBy)" asp-route-sortDirection="@(Model.sortDirection)" asp-route-pg="@(Model.TotalPages)">

                        Last

                    </a>

                </li>
            }
        </ul>
    }

</div>

Views/Shared/_Sorting.cshtml
@model CrudApplication1.Models.Sorting
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<tr class="text-center">
    <th>Id</th>
    <th>
        Name
        
    </th>
    <th>
        City
        
    </th>
    <th>
        State
        
    </th>
    <th>
        Salary
        
    </th>

    <th>Action</th>
</tr>